#!/usr/bin/env python

import json, urllib2, argparse, sys, base64

parser = argparse.ArgumentParser(description='Check a URL that returns JSON and emit the message and exit with the given exit code')
parser.add_argument('url', metavar = 'url', type = str)
parser.add_argument('--auth', metavar = 'auth', type = str)
args = parser.parse_args()

try:
    request = urllib2.Request(args.url)
    if args.auth:
        base64string = base64.b64encode(args.auth)
        request.add_header("Authorization", "Basic %s" % base64string)

    content = urllib2.urlopen(request)
    response = json.load(content)

    if not response.has_key('exitcode'):
        raise ValueError('exitcode not found in JSON response')

    if not response.has_key('message'):
        raise ValueError('message not found in JSON response')

    print response['message']
    sys.exit(response['exitcode'])

except Exception as err:
    print 'Error loading', args.url, '-', str(err)
    sys.exit(2)
